server:
  port: 8082

spring:
  application:
    name: transforma-eventos-microservicio

  # Configuración de base de datos H2 (desarrollo)
  datasource:
    url: jdbc:h2:mem:transforma_ecuador
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuración de Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: microservicio-eventos-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 300000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 1
        buffer.memory: 33554432

# Configuración de logging
logging:
  level:
    com.claro.ecuador.eventos: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/transforma-eventos.log

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka
  endpoint:
    health:
      show-details: always

# Información de la aplicación
info:
  app:
    name: Transforma Ecuador - Microservicio Eventos
    description: Microservicio para procesamiento de eventos Salesforce
    version: 1.0.0
    team: Global HITSS
    client: Claro Ecuador